### ISSUE TITLE
Create templates (design\layout) of pages

### ISSUE THREAD

**Issue by Rtiscev** [noooomad/projectWEB#1]
You must create a layout for the webpages (button goes there,   text is placed there, etc..). 
It's advised to use [Figma](figma.com)

**Comment by noooomad** [comment]
https://www.figma.com/file/rx4sLvwmybResKdhXfsOra/Untitled?type=design&node-id=0-1&t=3dIujIvnD3p6J5qR-0
![project](https://user-images.githubusercontent.com/123060314/236889972-794ec5b0-6160-4547-bb40-123eec94e483.png)
