### ISSUE TITLE
DB entities

### ISSUE THREAD

**Issue by Rtiscev** [noooomad/projectWEB#2]
Finish the Data Base diagram. Add more entities to the data base on design level, implementing it will be the next step
![image](https://user-images.githubusercontent.com/98522787/235954088-422d6c90-7f53-4044-88d3-138bca4c8220.png)
the pic above is just a template
![image](https://user-images.githubusercontent.com/98522787/235954264-eea33f84-1005-45e1-abed-cd46c300bc18.png)
this pic is a working DB diagram, you could use this as the inspiration.
(Need to add entity describing order, ingredients and others)

**Comment by noooomad** [comment]
Done
