### ISSUE TITLE
Creating SQL Script

### ISSUE THREAD

**Issue by Rtiscev** [noooomad/projectWEB#4]
Your final script should look something like this:
[sqlfinal.txt](https://github.com/noooomad/projectWEB/files/11384902/sqlfinal.txt)
(obviously, it's just a template generated by the SQL Server Management Studio, but it works)
You may refer to that file as a template, but do not use it as ur own, since it doesn't fit your system.
To learn how to make basic SQL queries go to [sql](https://www.w3schools.com/SQl/default.asp).
YOU MUST THINK UP #2 AND HAVE SQL SOFTWARE INSTALLED #3

**Comment by noooomad** [comment]
Also done
